# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/Exercises/chapter07/findandreplacedlg.ui'
#
# Created: Sun Apr 10 10:56:53 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_FindReplaceDlg(object):
    def setupUi(self, FindReplaceDlg):
        FindReplaceDlg.setObjectName("FindReplaceDlg")
        FindReplaceDlg.resize(341, 134)
        self.horizontalLayout_5 = QtGui.QHBoxLayout(FindReplaceDlg)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(FindReplaceDlg)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.find_line_edit = QtGui.QLineEdit(FindReplaceDlg)
        self.find_line_edit.setObjectName("find_line_edit")
        self.gridLayout.addWidget(self.find_line_edit, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(FindReplaceDlg)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.replace_line_edit = QtGui.QLineEdit(FindReplaceDlg)
        self.replace_line_edit.setObjectName("replace_line_edit")
        self.gridLayout.addWidget(self.replace_line_edit, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.case_check_box = QtGui.QCheckBox(FindReplaceDlg)
        self.case_check_box.setChecked(True)
        self.case_check_box.setObjectName("case_check_box")
        self.horizontalLayout.addWidget(self.case_check_box)
        self.whole_check_box = QtGui.QCheckBox(FindReplaceDlg)
        self.whole_check_box.setChecked(True)
        self.whole_check_box.setObjectName("whole_check_box")
        self.horizontalLayout.addWidget(self.whole_check_box)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(FindReplaceDlg)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.syntax_combo_box = QtGui.QComboBox(FindReplaceDlg)
        self.syntax_combo_box.setObjectName("syntax_combo_box")
        self.syntax_combo_box.addItem("")
        self.syntax_combo_box.addItem("")
        self.horizontalLayout_2.addWidget(self.syntax_combo_box)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 48, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.line = QtGui.QFrame(FindReplaceDlg)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.find_button = QtGui.QPushButton(FindReplaceDlg)
        self.find_button.setObjectName("find_button")
        self.verticalLayout_2.addWidget(self.find_button)
        self.replace_button = QtGui.QPushButton(FindReplaceDlg)
        self.replace_button.setObjectName("replace_button")
        self.verticalLayout_2.addWidget(self.replace_button)
        self.replace_all_button = QtGui.QPushButton(FindReplaceDlg)
        self.replace_all_button.setObjectName("replace_all_button")
        self.verticalLayout_2.addWidget(self.replace_all_button)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.close_button = QtGui.QPushButton(FindReplaceDlg)
        self.close_button.setObjectName("close_button")
        self.verticalLayout_2.addWidget(self.close_button)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.label.setBuddy(self.find_line_edit)
        self.label_2.setBuddy(self.replace_line_edit)

        self.retranslateUi(FindReplaceDlg)
        QtCore.QObject.connect(self.close_button, QtCore.SIGNAL("clicked()"), FindReplaceDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(FindReplaceDlg)
        FindReplaceDlg.setTabOrder(self.find_line_edit, self.find_button)
        FindReplaceDlg.setTabOrder(self.find_button, self.replace_line_edit)
        FindReplaceDlg.setTabOrder(self.replace_line_edit, self.replace_button)
        FindReplaceDlg.setTabOrder(self.replace_button, self.case_check_box)
        FindReplaceDlg.setTabOrder(self.case_check_box, self.whole_check_box)
        FindReplaceDlg.setTabOrder(self.whole_check_box, self.replace_all_button)
        FindReplaceDlg.setTabOrder(self.replace_all_button, self.syntax_combo_box)
        FindReplaceDlg.setTabOrder(self.syntax_combo_box, self.close_button)
        FindReplaceDlg.setTabOrder(self.close_button, FindReplaceDlg.syntax_combo_box_2)
        FindReplaceDlg.setTabOrder(FindReplaceDlg.syntax_combo_box_2, FindReplaceDlg.case_check_box_2)
        FindReplaceDlg.setTabOrder(FindReplaceDlg.case_check_box_2, FindReplaceDlg.whole_check_box_2)

    def retranslateUi(self, FindReplaceDlg):
        FindReplaceDlg.setWindowTitle(QtGui.QApplication.translate("FindReplaceDlg", "Find and Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FindReplaceDlg", "Find &what", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("FindReplaceDlg", "Replace w&ith", None, QtGui.QApplication.UnicodeUTF8))
        self.case_check_box.setText(QtGui.QApplication.translate("FindReplaceDlg", "&Case sensitive", None, QtGui.QApplication.UnicodeUTF8))
        self.whole_check_box.setText(QtGui.QApplication.translate("FindReplaceDlg", "Wh&ole words", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("FindReplaceDlg", "&Syntax", None, QtGui.QApplication.UnicodeUTF8))
        self.syntax_combo_box.setItemText(0, QtGui.QApplication.translate("FindReplaceDlg", "Literal text", None, QtGui.QApplication.UnicodeUTF8))
        self.syntax_combo_box.setItemText(1, QtGui.QApplication.translate("FindReplaceDlg", "Regular expression", None, QtGui.QApplication.UnicodeUTF8))
        self.find_button.setText(QtGui.QApplication.translate("FindReplaceDlg", "&Find", None, QtGui.QApplication.UnicodeUTF8))
        self.replace_button.setText(QtGui.QApplication.translate("FindReplaceDlg", "&Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.replace_all_button.setText(QtGui.QApplication.translate("FindReplaceDlg", "Replace &all", None, QtGui.QApplication.UnicodeUTF8))
        self.close_button.setText(QtGui.QApplication.translate("FindReplaceDlg", "Close", None, QtGui.QApplication.UnicodeUTF8))

